source 'https://rubygems.org'

gem 'rails', '3.2.14'

#gem 'sqlite3'
gem 'pg'
gem 'polylines'
gem 'ejs'
gem 'composite_primary_keys'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'sass-rails',   '~> 3.2.3'
gem 'compass-rails'

gem 'httparty'
gem 'jquery-rails'
gem 'tire' # elasticsearch wrapper
gem 'nokogiri'
gem 'whenever'

gem 'rubyzip'

gem 'redis'
gem 'activerecord-import'
gem 'mongoid'

# User profiles
gem 'devise'
gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-google-oauth2'

group :test, :development do
  gem 'rspec-rails' # testing framework
  gem 'capybara' # user simulation
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'meta_request'
end

#To work with Car2Go's webpage
gem 'mechanize'

#Push notifications
gem 'grocer'
gem 'gcm'

# Stripe payments
gem 'stripe'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# To use debugger
# gem 'debugger'
